imports:
    - { resource: config.yml }

framework:
    test: ~

parameters:
    upload_directory: "tests/Fixtures/"
    file_collection_prefix: "example-"
    access_list:
        - "code-for-tests"
